name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate snake svg
        uses: Platane/snk@v3
        with:
          github_user_name: zqzlq
          outputs: |
            dist/github-contribution-grid-snake-dark.svg
            dist/github-contribution-grid-snake.svg

      - name: Commit and push
        run: |
          cd dist
          [ -d .git ] && chmod -R u+w .git
          rm -rf .git
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update snake animation"
          git push -f https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:output
